# SPDX-FileCopyrightText: Copyright Siemens 2026
# SPDX-License-Identifier: Apache-2.0
# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags"
  behavior: default
