# SPDX-FileCopyrightText: Copyright Siemens 2026
# SPDX-License-Identifier: Apache-2.0
version = 0.1

[default.deploy.parameters]
stack_name = "pcf-fusion-app"
resolve_s3 = true
s3_prefix = "pcf-fusion-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# Credentials: admin/admin for all environments. For uhlmann use: Environment="uhlmann" BasicAuthUsername="admin" BasicAuthPassword="admin"
parameter_overrides = "Environment=\"dev\" BasicAuthUsername=\"admin\" BasicAuthPassword=\"admin\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
